### ISSUE TITLE
Možnosť stiahnúť repo?

### ISSUE THREAD

**Issue by virgo47** [HalasP/PosAmUloha#1]
Dobrý deň
Keď sme zadávali úlohu uchádzačom, tak sme predpokladali, že to nebudú publikovať z celkom pochopiteľných dôvodov. Bolo by, prosím Vás, možné, daný repozitár zmazať alebo, ak to váš GitHub plán umožňuje, aspoň sprivátniť?
Veríme, že zverejnenie bolo len pre Vaše potreby a nie zlomyseľnosť.
Ďakujem

Richard Richter
PosAm

**Comment by HalasP** [comment]
Dobry den,
publikoval som to preto, aby si to mohli vasi kolegovia dopredu pozriet.
Som velmi zvedavy v com vam toto repo prekaza?
Neobsahuje ani zadanie a ani riesenie.
Dakujem

**Comment by virgo47** [comment]
Ah... potom pardon. Ja som to nepozeral do hlbky, az teraz vidim, ze to neobsahuje samotny "solver", aj ked by sa asi dali pouzit parsovacie casti. Vseobecne by som pri pohovorovych ulohach cakal, ze ziadna stopa po nich (aspon ta lahko dohladatelna) neprezije proces pohovoru, ale samozrejme vynutit si to nevieme, ak to teda kandidata nenechame robit pred nami na nasich pocitacoch, co je pri takejto ulohe nezmysel. :-)
Samozrejme, nemozem nijako zabranit tomu, ze zmienka o ulohe na internete ostane, len sa tomu netesime. Najma, ked sa da lahko vyhladat. To je vsetko.
RR
